version: '3.8'

services:
  ms-user:
    build: .
    container_name: ms-user
    network_mode: bridge
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:az2aoY8NFvC2P72x@db.lutorvywewujktkywase.supabase.co:5432/postgres
      PORT: 3000
    command: sh -c "apk add --no-cache bind-tools && npm start"
    restart: unless-stopped